##############################################################################################
# DO NOT CHANGE ANYTHING IN THIS FILE! Go to ~/.config/hypr/Sources to find EDITABLE things! #
##############################################################################################
# If you do change anything in this file, the rice MAY break. DO NOT CHANGE. SERIOUSLY. <3   #
##############################################################################################

source = ~/.config/hypr/Sources/theme.conf
source = ~/.config/hypr/Sources/programs.conf
source = ~/.config/hypr/Sources/monitors.conf
source = ~/.config/hypr/Sources/input.conf
source = ~/.config/hypr/Sources/keybinds.conf
source = ~/.config/hypr/Sources/win_workspace.conf

exec-once = waybar & hyprpaper
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

